name: 'Arm Tool License'
description: 'Activate Arm user-based license'
author: 'Jonatan Antoni <jonatan.antoni@arm.com'

inputs:
  server:
    description: A license server to get product license from.
    required: false
    default: "https://mdk-preview.keil.arm.com"
  product:
    description: The product to get license for.
    required: false
    default: "KEMDK-COM0"
  code:
    description: License activation code.
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ -n "${{ inputs.code }}" ]]; then
          armlm activate --server ${{ inputs.server }} --code ${{ inputs.code }}
        else
          armlm activate --server ${{ inputs.server }} --product ${{ inputs.product }}
        fi
