on: 
  pull_request: 
    branches: main
    paths:
      - vcpkg/*
      - .github/workflows/vcpkg-action.yml
  push:
    branches: main
    paths:
      - vcpkg/*
      - .github/workflows/vcpkg-action.yml
  workflow_dispatch:

jobs:
  test:
    name: Test vcpkg action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate vcpkg environment
        uses: ./vcpkg
        with:
          config: ./vcpkg/vcpkg-configuration.json

      - name: Verify some tools
        run: |
          which cpackget
          which cbuild
